### ISSUE TITLE
Daily average 79 hours

### ISSUE THREAD

**Issue by pedroresende** [datreks/codetime-vscode#16]
![image](https://user-images.githubusercontent.com/951377/153750280-66da11da-2124-47ec-8f4c-bfa685c9e65d.png)

**Comment by si9ma** [comment]
@pedroresende I'll check later!

**Comment by Jannchie** [comment]
I apologize for the delayed response and any inconvenience it may have caused. Thank you for bringing to my attention the issue regarding the statistical calculation. After investigating the matter, I have found that the problem was caused by an incorrect statistical calculation.

To ensure that this issue does not happen again, I have rewritten the entire backend to use a new statistical algorithm. This will help to avoid any further incorrect results and ensure that all future calculations are accurate.

Thank you for your patience and understanding while we worked to resolve this issue. If you have any further concerns or questions, please do not hesitate to reach out.
