### ISSUE TITLE
Different times on dashboards

### ISSUE THREAD

**Issue by thiagolopes-dev** [datreks/codetime-vscode#29]
Good morning, first congratulations on the beautiful project you have developed.

I noticed the following situation https://codetime.datreks.com/
the dashboard returns me a value of 1193hrs 29mins that has not changed.. and if I use its token in the visual code it shows 0sec.

but I noticed this new dashboard
https://codetime.dev/dashboard which shows 928hrs 39mins using token in visual code shows 44hrs.

after all, which token should I use from which platform?

because both are not with correct values.

**Comment by Jannchie** [comment]
We're really sorry for the trouble.

If you set the api entry to `codetime-api.datreks.com`, you should use the token on `codetime.datreks.com`.

If the api entry is set to `api.codetime.dev,` you should use the tokens provided in `codetime.dev`, but they are probably the same.

Neither is accurate, `codetime.datreks.com` has some duplications, and the server is unstable and sometimes unable to record. `codetime.dev` is still under development and is expected to provide a more stable service and eliminate the problem of double counting.

In the future, we will move all services and data to `codetime.dev`. I would recommend you to use it, but unfortunately, due to some server problems, it is currently out of service and will not be restored until the end of this month.

So at this point in time, it's recommended that you use `codetime.datreks.com` and use `codetime-api.datreks.com` as api entry. In the future, we will move data from datreks to `codetime.dev` and eliminate duplicates of data (which will make statistics shorter).

---

> in visual code shows 44hrs.

This could be a bug if extension settings set to display code time for 24 hours. I will address this bug.

---

Thank you very much for your continued attention and use of our service. I am deeply ashamed that I have not been able to provide stable service.

**Comment by thiagolopes-dev** [comment]
then you recommend that you use codetime.dev, I will use it. Thanks for the reply and don't feel ashamed, the design is magnificent.

**Comment by Jannchie** [comment]
We appreciate your support and would like to inform you that our service has now been fully restored to normal. We acknowledge that we may not have performed up to our best in the past, but moving forward, we will make every effort to ensure the stability of our service.
